type Event {
    id: String!
    name: String!
}

input CreateEventInput {
    name: String!
}

type Query {
    events: [Event!]!
}

type Mutation {
    createEvent(input: CreateEventInput!): Event!
}